# MySQL Database Configuration (Aiven Cloud)
spring.datasource.url=jdbc:mysql://avnadmin:AVNS_qKyr3MlWJZytJoDc-xA@mysql-20dc3e49-shreyasharathk28-3a51.c.aivencloud.com:25132/defaultdb?useSSL=true&requireSSL=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_qKyr3MlWJZytJoDc-xA
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server Configuration
server.port=${PORT:8080}

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shreyasharathk28@gmail.com
spring.mail.password=mvgu kzmq ajpn hkji
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
